labels: ["Art competition"]
body:
  - type: markdown
    attributes:
      value: |
        ** Upload your picture and provide the following description. **
  - type: textarea
    id: art
    attributes:
      label: Your work
      description: "A description about suggestions to help you"
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Your Name
      description: A description about suggestions to help you
    validations:
      required: true
  - type: input
    id: tool
    attributes:
      label: Tool You Used
      description: A description about suggestions to help you
    validations:
      required: true
  - type: textarea
    id: short
    attributes:
      label: Short Description (up to 3 sentences)
      description: "A description about suggestions to help you"
      value: |
        For me, [*the chosen concept*] means [*the prompt sentence you used to generate the picture *]".
    validations:
      required: true
  - type: textarea
    id: long
    attributes:
      label: Long Description (up to 3 sentences)
      description: "A description about suggestions to help you"
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
