name: test

on:
  issues:
    types:
      - opened

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: my test
        uses: KihongHeo/test-action@v1.5
        id: dup_scan
        with:
          issue_num: ${{ github.event.issue.number }}
          issue_contents: ${{ github.event.issue.body }}
          repository_path_name: ${{ github.repository }}
          rapid_key: ${{ env.rapid_key }}
          repo_key: ${{ env.repo_key }}
      # Use the output from the `dup_scan` step
      - name: Get the output issue number
        run: echo "The output was ${{ steps.dup_scan.outputs.dup_num }}"
