name: test

on:
  issues:
    types:
      - opened

jobs:
  test:
    name: test
    runs-on: ubunu-latest
    steps:
      - use: actions/checkout@v3

      - name: my test
        uses: KihongHeo/test-action
